sudo: false
language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

matrix:
  fast_finish: true
  include:
    - env: TOXENV=qa
      python: "3.7"
    - env: TOXENV=py39-django-dev
      python: "3.9"
  exclude:
    # Python/Django combinations that aren't officially supported
    - { env: DJANGO=1.11, python: "3.8" }
    - { env: DJANGO=1.11, python: "3.9" }
  allow_failures:
    - env: DJANGO=1.8
    - env: DJANGO=1.11
    - env: TOXENV=qa
    - env: TOXENV=py37-django-dev


install: pip install tox-travis python-coveralls codecov
script: tox
after_success:
  - codecov -e TOXENV,DJANGO

# TODO
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel

  user: __token__
  password:
    # https://docs.travis-ci.com/user/encryption-keys/
    secure: "HBU0bntoCTJ8dlz+8fjdo9cFb6TVff0pcITDPqtBnKJ5pCEfEInSk794fMaOU/TXu9WB8uNrcQ57ojJiRWMt9m25pnRK3/WasD+ZrOedZZcS4e7jtbsSlp9WZVpvSzPq3P0jmBA754ZlBDA0Q90qviwuUN40LO9J8+e/2jv8UokuPMo2f4oxjzpnaoq51Gg+0MxQ0dQOiPo8bp8nO+ICiHoTl6He+gQBd/WaqbpTnylVzWnzi1WrkZi9oKyEq3RHt1JwPjlaH7jylEbZHTV73MgygKuFZE84A9/AqZi29bh9A8RDYw6bxNwYhNH9/ASxbf2HLDWb1t4m5hzOu26SQaij7O437RgtKncoqVn8OOrTYJnIWsCanLWGYj9NanzK7uyzaTOXGfmX/36ch0vSBDw7V7iWoJE4dpr4Pwn2Jjf/NYYJDlhEHG9P5fSO6xKlPy6frs//p9aOia+pnSzr8kEBmF93vGjSXtsManC2GVqdDitD8CADKu/1WJX74oYrqIYUcKhbmj6xlnwN7g3EYN5kYHNvZHu+6yxoAIlkFxqoO8oHN617sOVYSv9nwLIazHXsIr6eozTYA4jvR747b9Ugf6mOFKxf5B6dJ06GX00yhIVAg8S6fYGMJ+B9eK9JiAxu8eXdgAoYA7bObL6pZoMWXt3KLf1hP2fskKNvF2Q="
  on:
    tags: true
    repo: Apkawa/django-modeltranslation-rosetta
    branch: master
